<?php
require_once('DatabaseHelper.php');

$database = new DatabaseHelper();

$fid = '';
if (isset($_GET['fid'])) {
    $fid = $_GET['fid'];
}

$stadt = '';
if (isset($_GET['stadt'])) {
    $stadt = $_GET['stadt'];
}

$land = '';
if (isset($_GET['land'])) {
    $land = $_GET['land'];
}

$adresse = '';
if (isset($_GET['adresse'])) {
    $adresse = $_GET['adresse'];
}

//Fetch data from database
$locations_array = $database->selectAllLocations($fid, $stadt, $land, $adresse);
?>

<html>
<head>
    <style>body {
            background-image: linear-gradient(#87d9fa, #7abaff);
        }
    </style>
    <meta charset="utf-8">
    <title>Best Cars</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="style.css">
</head>

<body>


<div style="background-image: url('car_1.jpeg');
background-position: center;
background-repeat: no-repeat;
background-size: cover;
height: 800px;
padding-top: 0;">

    <h1 style="color: cadetblue; text-shadow: 5px 3px 7px black;
-webkit-text-stroke-width: 1px;
  -webkit-text-stroke-color: steelblue;">Best Cars</h1>

</div>


<br>

<h2>Our Locations:</h2>
<div class="tableContainer">
    <table class="table">
        <thead class="head">
        <tr>
            <th class="col">ID</th>
            <th class="col">Country</th>
            <th class="col">City</th>
            <th class="col4">Address</th>
        </tr>
        </thead>
        <?php foreach ($locations_array as $location): ?>
            <tr>
                <td><?php echo $location['FID']; ?>  </td>
                <td><?php echo $location['LAND']; ?>  </td>
                <td><?php echo $location['STADT']; ?>  </td>
                <td><?php echo $location['ADRESSE']; ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
<br>
<br>


<div class="flex-container">

    <div class="form">
        <!-- Search form -->
        <h3>Location Search:</h3>
        <form method="get">

            <table class="table2">
                <!-- ID textbox:-->
                <tr class="spaceunder">
                    <td><label for="fid">ID:</label></td>
                    <td><input id="fid" name="fid" type="text" value='<?php echo $fid; ?>' min="0"></td>
                </tr>
                <br>
                <!-- Country textbox:-->
                <tr class="spaceunder">
                    <td><label for="land">Country:</label></td>
                    <td><input id="land" name="land" type="text" value='<?php echo $land; ?>' maxlength="20"></td>
                </tr>
                <br>

                <!-- City textbox:-->
                <tr class="spaceunder">
                    <td><label for="stadt">City:</label></td>
                    <td><input id="stadt" name="stadt" type="text" value='<?php echo $stadt; ?>' maxlength="20"></td>
                </tr>

                <br>
            </table>
            <br>

            <!-- Submit button -->
            <div style="margin: auto;
                width: 15%;
                padding: 20px; ">
                <button id='submit' type='submit'>
                    Search
                </button>
            </div>
        </form>
    </div>
    <br>
    <hr>

    <!-- Add Location -->
    <div class="form">
        <h3>Add Location: </h3>

        <form method="post" action="addLocation.php">
            <!-- ID is not needed, because its autogenerated by the database -->
            <table class="table2">
                <!-- Country textbox -->
                <tr class="spaceunder">
                    <td><label for="new_country">Country:</label></td>
                    <td><input id="new_country" name="country" type="text" maxlength="20"></td>
                </tr>
                <br>

                <!-- City textbox -->
                <tr class="spaceunder">
                    <td><label for="new_city">City:</label></td>
                    <td><input id="new_city" name="city" type="text" maxlength="20"></td>
                </tr>
                <br>

                <!-- Address textbox -->
                <tr>
                    <td><label for="new_address">Address:</label></td>
                    <td><input id="new_address" name="address" type="text" maxlength="20"></td>
                </tr>

            </table>
            <br>


            <!-- Submit button -->
            <div style="margin: auto;
                width: 18%;
                padding: 20px;">
                <input type="submit" name="button" value="Add Location">

            </div>

        </form>
    </div>

    <br>
    <br>

    <!-- Choose Location -->
    <div class="form">
        <h3>Choose Location: </h3>
        <form method="post" action="chosenLocation.php">
            <!-- ID is not needed, because its autogenerated by the database -->
            <table class="table2">
                <!-- ID textbox -->
                <tr class="spaceunder">
                    <td><label for="new_name">ID:</label></td>
                    <td><input id="new_name" name="id" type="text" maxlength="20"></td>
                </tr>
                <br>

            </table>
            <br>

            <!-- Submit button -->
            <div style="margin: auto;
                width: 18%;
                padding: 20px;">
                <button type="submit">
                    Choose
                </button>
            </div>
        </form>
    </div>

    <hr>

    <div class="form">
        <!-- Delete Location -->
        <h3>Delete Location: </h3>
        <form method="post" action="delLocation.php">
            <!-- ID textbox -->
            <table class="table2">
                <tr class="spaceover">
                    <td><label for="del_name">ID:</label></td>
                    <td><input id="del_name" name="id" type="number" min="0"></td>
                </tr>
            </table>
            <br>
            <!-- Submit button -->
            <div class="button">
                <button type="submit">
                    Delete
                </button>
            </div>
        </form>
    </div>

    <hr>

</div>


</body>
</html>